// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcluQ93IePnGgapkFVZC3WiNECq5mnN80',
    appId: '1:33992045759:web:27ad2972b3993b41b3420a',
    messagingSenderId: '33992045759',
    projectId: 'flutter-chat-app-478da',
    authDomain: 'flutter-chat-app-478da.firebaseapp.com',
    storageBucket: 'flutter-chat-app-478da.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEU0SMuAs2G5d5zmgVo1L_b4HdCSntopo',
    appId: '1:33992045759:android:c815313a7947aa49b3420a',
    messagingSenderId: '33992045759',
    projectId: 'flutter-chat-app-478da',
    storageBucket: 'flutter-chat-app-478da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx3NgKrfQOcylbNr6-ygLd3OspkjeMODM',
    appId: '1:33992045759:ios:5cbf4d028bf82466b3420a',
    messagingSenderId: '33992045759',
    projectId: 'flutter-chat-app-478da',
    storageBucket: 'flutter-chat-app-478da.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx3NgKrfQOcylbNr6-ygLd3OspkjeMODM',
    appId: '1:33992045759:ios:626fd6a7848bc498b3420a',
    messagingSenderId: '33992045759',
    projectId: 'flutter-chat-app-478da',
    storageBucket: 'flutter-chat-app-478da.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
